### ISSUE TITLE
snbc 2300

### ISSUE THREAD

**Issue by abdkaviani** [pbosakov/image2zpl#2]
Hello

We have SNBC label printer 2300 with BPLZ language.
My printer is connected to LAN through print server and your function works for me very well, as this:

$labelName = "BARCODE".$barcode; 
$Data .= wbmp_to_zpl($myImage,$labelName); 
$Data .= "^XA"; 
$Data .= "^FO5,20^XGR:".$labelName.".GRF,1,1^FS"; 
$Data .= "^XZ";

Tanks a lot

**Comment by pbosakov** [comment]
Thank you for your feedback. I am happy it works for you.
